/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package algoliasearch.client.kotlin.example

import com.algolia.search.client.ClientSearch
import com.algolia.search.model.*
import com.algolia.search.model.search.Query
import com.algolia.search.serialize.KeyObjectID
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put


fun initializeIndex() {
    val client = ClientSearch(
        applicationID = ApplicationID("application-id"),
        apiKey = APIKey("api-key")
    )

    val indexName = IndexName("test_index")

    val index = client.initIndex(indexName)

    val json = (1..1001)
        .map {buildJsonObject {
            put(KeyObjectID, it)
        }}.toList()

    runBlocking {
        index.saveObjects(json)
    }
}



fun main() {

    initializeIndex()

    val client = ClientSearch(
        applicationID = ApplicationID("application-id"),
        apiKey = APIKey("api-key")
    )
    val indexName = IndexName("test_index")

    val index = client.initIndex(indexName)

    val query = Query(
        filters = (1..1001).toList().joinToString(" OR ") { "objectID:${it}" },
        attributesToRetrieve = listOf(
            Attribute(KeyObjectID)
        )
    )
    runBlocking {
        val res = index.browseObjects(query)
    }
}
