/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package algoliasearch.client.kotlin.example

import com.algolia.search.client.ClientSearch
import com.algolia.search.model.*
import com.algolia.search.model.indexing.Partial
import kotlinx.coroutines.runBlocking

fun main() {
    val client = ClientSearch(
        applicationID = ApplicationID("application-id"),
        apiKey = APIKey("api-key")
    )
    val indexName = IndexName("test_index")

    val index = client.initIndex(indexName)

    val partialLastModified = Partial.IncrementSet(Attribute("lastmodified"), 1593431913)
    val partialAddUnique = Partial.AddUnique(Attribute("_tags"), "public")
    runBlocking {
        index.partialUpdateObjects(
            listOf(
                ObjectID("0") to partialLastModified,
                ObjectID("0") to partialAddUnique,
            )
        )
    }
}
